'use client';
import {useEffect,useMemo,useState} from "react";
function getId(url:string){try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return u.pathname.slice(1);if(u.searchParams.get("v"))return u.searchParams.get("v");const m=u.pathname.match(/\/shorts\/([^/]+)/);return m?.[1]||null}catch{return null}}
export default function Home(){const [url,setUrl]=useState(""),[comments,setComments]=useState<string[]>(Array(100).fill("")),[status,setStatus]=useState<string[]>(Array(100).fill("Not posted")),[logged,setLogged]=useState(false),[posting,setPosting]=useState(false),id=useMemo(()=>getId(url),[url]);
useEffect(()=>{fetch("/api/auth/status").then(r=>r.json()).then(d=>setLogged(!!d.loggedIn)).catch(()=>{});},[]);
const update=(i:number,v:string)=>{setComments(c=>{const n=[...c];n[i]=v;return n});setStatus(s=>{const n=[...s];n[i]="Not posted";return n})};
const postOne=async(i:number)=>{if(!id||!comments[i].trim())return false;setStatus(s=>{const n=[...s];n[i]="Posting…";return n});try{const r=await fetch("/api/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videoId:id,comment:comments[i]})});const d=await r.json();setStatus(s=>{const n=[...s];n[i]=r.ok?"Posted on YouTube":d.error||"Post failed";return n});if(r.status===401)setLogged(false);return r.ok}catch{setStatus(s=>{const n=[...s];n[i]="Post failed";return n});return false}};
const postWithConfirmations=async()=>{if(!id||posting)return;const pending=comments.map((c,i)=>({c:c.trim(),i})).filter(x=>x.c&&status[x.i]!=="Posted on YouTube");if(!pending.length)return;setPosting(true);for(const item of pending){const ok=window.confirm("Post Comment "+(item.i+1)+" to YouTube?\n\n"+item.c);if(!ok){setStatus(s=>{const n=[...s];n[item.i]="Skipped";return n});continue}const success=await postOne(item.i);if(!success)break}setPosting(false)};
const login=()=>{window.location.href="/api/auth/login"};
const pendingCount=comments.filter((c,i)=>c.trim()&&status[i]!=="Posted on YouTube").length;
return <main><div className="card"><div className="badge">YOUTUBE COMMENT TOOL</div><h1>100 Comment Boxes</h1><p className="sub">Sign in with the Google/YouTube account you want to use, then review each comment before it is posted.</p>
<div className="auth"><span>{logged?"✓ YouTube account connected":"YouTube account not connected"}</span><button onClick={login}>{logged?"Reconnect Google":"Sign in with Google"}</button></div>
<label>Video URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=..."/>{id?<div className="video"><iframe src={"https://www.youtube.com/embed/"+id} title="YouTube video" allowFullScreen/></div>:<div className="hint">Enter a valid YouTube video URL to see the preview.</div>}
<div className="notice">The final button reviews each filled comment one by one. A comment is posted only after you confirm that specific comment.</div>
<div className="comment-list">{comments.map((comment,i)=><div className="comment-box" key={i}><div className="comment-head"><strong>Comment {i+1}</strong><span>{comment.length}/5000</span></div><textarea maxLength={5000} value={comment} onChange={e=>update(i,e.target.value)} placeholder={"Write comment "+(i+1)+"..."}/><div className="row"><span>{status[i]}</span></div></div>)}</div>
<button className="post-all" disabled={!id||!logged||!pendingCount||posting} onClick={postWithConfirmations}>{posting?"Processing…":"Comment Submit ("+pendingCount+")"}</button>
<a className="yt" href={id?("https://www.youtube.com/watch?v="+id):"https://www.youtube.com"} target="_blank">Open on YouTube ↗</a></div></main>}
